namespace Amilious.ProceduralTerrain.Map.Enums {
    
    /// <summary>
    /// This enum is used to represent the type of map.
    /// </summary>
    public enum MapType {
        
        /// <summary>
        /// This value indicates that the map should be endlessly generated by chunks.
        /// </summary>
        EndlessChunkBased,
        
        /// <summary>
        /// This value indicates that the map should be endlessly generated by regions.
        /// </summary>
        EndlessRegionBased,
        
        /// <summary>
        /// This value indicates that the world has a set size and is generated by chunks.
        /// </summary>
        SetSizeChunkBased,
        
        /// <summary>
        /// This value indicates that the world has a set size and is generated by regions.
        /// </summary>
        SetSizeRegionBased
    }
}